[[redirects]]
  from = "/api/history"
  to = "/.netlify/functions/history"
  status = 200

[[redirects]]
  from = "/api/trakt-token"
  to = "/.netlify/functions/trakt-token"
  status = 200

[[redirects]]
  from = "/api/goodreads"
  to = "/.netlify/functions/goodreads"
  status = 200

[[redirects]]
  from = "/api/lastfm"
  to = "/.netlify/functions/lastfm"
  status = 200

[build]
  command = "gatsby build"
  publish = "public"
  functions = "netlify/functions"

[dev]
  targetPort = 8000
  port = 8888